name: Create stable release

on:
  pull_request:
    branches: [main]

jobs:
  create-release:
    permissions:
      contents: write
    uses: workleap/wl-reusable-workflows/.github/workflows/create-stable-release.yml@feature/idp-3130_use_shared_token
